# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Kshitij Shah'
tagline:          'Data Scientist'
description:      'You will find (almost) everything important about me here.'
url:              http://xitizzz.github.io
baseurl:          /

email: kshitij.shah.cs@gmail.com
github_username:  xitizzz
linkedin_public_url: loremipsum

author:
  name:           'Kshitij '
  url:            https://twitter.com/xitizzz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://xitizzz.github.io


